### ISSUE TITLE
ViZDoom needs a writable home

### ISSUE THREAD

**Issue by ppwwyyxx** [Marqt/ViZDoom#102]
I noticed that vizdoom needs a writable home directory to create `~/.config` and `~/.config/vizdoom` directories.
Otherwise even simple examples like `python/fps.py` cannot run.

In cases I don't have a writable home, Is there anyway I could set the directory to some other places? Changing the HOME env var doesn't help.

Or is it OK if you could change the code to avoid creating those directory? 

Thanks a lot!

// I'm running code in a shared machine where everyone has a working directory, but HOME is not writable.

**Comment by wjaskowski** [comment]
Maybe you can try:

``HOME=somedir yourscript.py``

or

``
export HOME=somedir
yourscript.py
``


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by ppwwyyxx** [comment]
I've tried it and as I said, setting the HOME environment variable doesn't help.

**Comment by wjaskowski** [comment]
I think you can try to fix this by modifying all occurrences of ".config"
in the source files. If you fix the paths to use $HOME, then we will be
grateful for a pull request:

``
roo :: ~/projects/vizdoom ‹master*› » ack "\.config"
examples/c++/vizdoom.ini
8:Path=~/.config/vizdoom
18:Path=~/.config/vizdoom
26:Path=/home/wojciech/.config/vizdoom/autoexec.cfg
29:Path=/home/wojciech/.config/vizdoom/autoexec.cfg
32:Path=/home/wojciech/.config/vizdoom/autoexec.cfg
35:Path=/home/wojciech/.config/vizdoom/autoexec.cfg
38:Path=/home/wojciech/.config/vizdoom/autoexec.cfg

examples/python/_vizdoom.ini
8:Path=~/.config/vizdoom
18:Path=~/.config/vizdoom
26:Path=/home/wojciech/.config/vizdoom/autoexec.cfg
29:Path=/home/wojciech/.config/vizdoom/autoexec.cfg
32:Path=/home/wojciech/.config/vizdoom/autoexec.cfg
35:Path=/home/wojciech/.config/vizdoom/autoexec.cfg
38:Path=/home/wojciech/.config/vizdoom/autoexec.cfg

examples/python/vizdoom.ini
8:Path=~/.config/vizdoom
18:Path=~/.config/vizdoom
26:Path=/home/wojciech/.config/vizdoom/autoexec.cfg
29:Path=/home/wojciech/.config/vizdoom/autoexec.cfg
32:Path=/home/wojciech/.config/vizdoom/autoexec.cfg
35:Path=/home/wojciech/.config/vizdoom/autoexec.cfg
38:Path=/home/wojciech/.config/vizdoom/autoexec.cfg

src/vizdoom/src/version.h
102:#define GAME_DIR ".config/" GAMENAMELOWERCASE

src/vizdoom/src/d_iwad.cpp
376://  3. $HOME/.config/zdoom
522:  "1. Place one or more of these wads in ~/.config/" GAMENAMELOWERCASE
"/.\n"
523:  "2. Edit your ~/.config/" GAMENAMELOWERCASE "/" GAMENAMELOWERCASE
".ini and add the directories of your\n"

src/vizdoom/src/m_specialpaths.cpp
493: // Sanity check for ~/.config
494: FString configPath = NicePath("~/.config/");
499: I_FatalError ("Failed to create ~/.config directory:\n%s",
strerror(errno));
504: I_FatalError ("~/.config must be a directory");
551: FString path = NicePath("~/.config/zdoom/cache");
595: // Then check in ~/.config/zdoom/botfilename.
``

Also:

``
roo :: ~/projects/vizdoom ‹master*› » ack "\~\/"
examples/c++/vizdoom.ini
8:Path=~/.config/vizdoom
18:Path=~/.config/vizdoom

examples/python/_vizdoom.ini
8:Path=~/.config/vizdoom
18:Path=~/.config/vizdoom

examples/python/vizdoom.ini
8:Path=~/.config/vizdoom
18:Path=~/.config/vizdoom

cmake_modules/FindSDL2.cmake
78:  ~/Library/Frameworks

src/vizdoom/src/d_main.cpp
2100: file = NicePath("~/" GAME_DIR "/skins");

src/vizdoom/src/m_misc.h
56:FString GetUserFile (const char *path); // Prepends ~/.zdoom to path

src/vizdoom/src/gameconfigfile.cpp
116: SetValueForKey("Path", "~/" GAME_DIR, true);
135: SetValueForKey ("Path", "~/" GAME_DIR, true);
158: SetValueForKey ("Path", "~/" GAME_DIR, true);

src/vizdoom/src/d_iwad.cpp
518:  "1. Place one or more of these wads in ~/Library/Application
Support/" GAMENAMELOWERCASE "/\n"
519:  "2. Edit your ~/Library/Preferences/" GAMENAMELOWERCASE ".ini and add
the directories\n"
522:  "1. Place one or more of these wads in ~/.config/" GAMENAMELOWERCASE
"/.\n"
523:  "2. Edit your ~/.config/" GAMENAMELOWERCASE "/" GAMENAMELOWERCASE
".ini and add the directories of your\n"

src/vizdoom/src/m_specialpaths.cpp
452: path = "~/";
487: path = NicePath("~/" GAME_DIR "/");
493: // Sanity check for ~/.config
494: FString configPath = NicePath("~/.config/");
499: I_FatalError ("Failed to create ~/.config directory:\n%s",
strerror(errno));
504: I_FatalError ("~/.config must be a directory");
510: FString oldpath = NicePath("~/." GAMENAMELOWERCASE "/");
551: FString path = NicePath("~/.config/zdoom/cache");
595: // Then check in ~/.config/zdoom/botfilename.
630: return NicePath("~/" GAME_DIR "/screenshots/");
643: return NicePath("~/" GAME_DIR);
``

**Comment by ppwwyyxx** [comment]
I took a look at all the above appearance, and it seems like all `~/` ends up being processed by `NicePath` function in `cmdlib.cpp`.

This function expand `~` as well as `~username`, by looking at `/etc/passwd` (!). That's why setting $HOME doesn't work.
I can change it to use $HOME instead of `/etc/passwd`, for the `~` case, but keep things unchanged for the `~username` case (although I doubt it is used anywhere). This may sound a bit inconsistent, so I'm asking your opinion on this matter.

**Comment by Marqt** [comment]
Thank you @ppwwyyxx, this solution is definitely good enough and ~/.config/vizdoom is very rarely used in intended applications of ViZDoom.
