### ISSUE TITLE
Hide multikill messages

### ISSUE THREAD

**Issue by ppwwyyxx** [Marqt/ViZDoom#104]
I tried setting 
```
render_hud = false
render_crosshair = false
render_weapon = false
render_decals = false
render_particles = false
```
But still could see text like "double kill" on the bottom and "AI is on a rampage" on the top got rendered. Is there anyway to disable this?

**Comment by Marqt** [comment]
I've just checked again and unfortunately it looks like there is no way to disable this messages using engine options. I'll change code to hide them when `render_hud == False`.

**Comment by wjaskowski** [comment]
I propose to make it a new option (for backward compatibility)

**Comment by Marqt** [comment]
I was wrong, there are CVARs responsible for this.
Add `game.add_game_args(+cl_showmultikills 0 +cl_showsprees 0)` to disable them.

But I still think that function to turn them on and off from code would be useful.
