### ISSUE TITLE
Depth buffer for 'on my way home' scenario not working

### ISSUE THREAD

**Issue by shehroze37** [Marqt/ViZDoom#105]
Hi the depth buffer for on my way home scenario is not working. And what metric does the depth buffer values represent. I am using that for research and its very important I get the scale of that correct so wasn't sure how to convert those depth values into a suitable metric i.e (meters, cm, mm etc). I would appreciate any help on this. Even if it doesnt represent any metric, are the depth buffer values consistent throughout different scenarios?

When I was testing the on my way home scenario, the max value in the depth buffer was 4 and the minimum was 4 as well so not sure whats going wrong there.

Cheers !

**Comment by Marqt** [comment]
It's strange but it actually doesn't work for this one scenario. I'll examine this.

And as for the question about metric:
It is not intended to represent any and the values are the same for the same distances regardless of the scenario and main wad.

So using this [http://doomwiki.org/wiki/Map_unit](http://doomwiki.org/wiki/Map_unit) and a map with known dimensions you can calculate how to translate buffer's values to real world units.

Let us know if you do it, I'm curious about results :)

**Comment by oOo0oOo** [comment]
I found it is possible to get the correct depth buffer in my_way_home.
Its just not very likely and doesn't work if you render the window. 
In general this looks a lot like [issue 72](https://github.com/Marqt/ViZDoom/issues/72).

A little experiment (see code below):

1) Turning off all rendering options (incl window):
Found 6.5 % correct depth buffers (65/1000) in 233.9 s.

2) Turning on all rendering options (except window):
Found 13.4 % correct depth buffers (134/1000) in 228.6 s.

3) Turning on all rendering options (incl window):
Found 0.0 % correct depth buffers (0/500) in 333.1 s.



```python
import numpy as np
from vizdoom import DoomGame, ScreenFormat

import time


def create_game(config_path = 'config/my_way_home.cfg'):
    '''
        Create and initialize a new game
        Set screenformat manually
        Start a new episode
    '''
    game = DoomGame()
    game.load_config(config_path)
    game.set_screen_format(ScreenFormat.CRCGCBDB) # Set screenformat manually
    game.init()
    game.new_episode()
    return game


def functional_depth_buffer():
    game = create_game()
    img_buffer = game.get_state().image_buffer
    depth = img_buffer[-1,:,:]

    # Test if correct depth buffer this can be incorrect because
    # standing straight in front of a wall might result in a uniform depth buffer.
    if np.std(depth) > 0.0001:
        functional = True
    else:
        functional = False

    game.close()

    return functional


def test_functional_depth_buffer(n = 100):
    n_funct = 0.
    for i in xrange(n):
        if functional_depth_buffer():
            n_funct += 1
    return round(n_funct/n,3)


if __name__ == '__main__':
    n = 500
    before = time.time()
    r_funct = test_functional_depth_buffer(n)
    duration = round(time.time() - before,1)
    print 'Found {} % correct depth buffers ({}/{}) in {} s.'.format(r_funct*100., int(n*r_funct), n, duration)
```

**Comment by Marqt** [comment]
I cannot reproduce this bug anymore (tested on Linux and Windows).
