### ISSUE TITLE
ViZDoomErrorException: Unexpected ViZDoom instance crash randomly after a lot of episodes.

### ISSUE THREAD

**Issue by rubenfiszel** [Marqt/ViZDoom#106]
Hello,

I had this error after 300 000 steps of training (around 1200 episodes) on Deadly Corridor (2 days or DQN training). The error is not very informative and I can't fallback from it. A bit annoying.

master branch, up-to-date, java bindings.

**Comment by Marqt** [comment]
Why can't you fallback? There is something wrong with exception handling in java binding?

There are 2 possible causes of this:
- ViZDoom crashed, in most cases vizdoom-log.txt should be created in working dir with more info (also window should pop up).
- ViZDoom game process was terminated by external signal.

**Comment by rubenfiszel** [comment]
Hello,

In the java-binding, make action does not throw vizdoom exception so I could not surround it with the appropriate try-catch.

So here is my hypothesis, I run out of memory (which could have happened because of a misconfiguration of my RL agent) and vizdoom crashed from lack of memory.

I am currently testing this hypothesis with a new training http://54.218.52.133:8080/training/12 and will keep you updated. Thank you for your answer :)

**Comment by Marqt** [comment]
I'm sorry, that exception re-throwing to Java doesn’t work properly. We will fix this flaw.
http://54.218.52.133:8080/training/12 <- wow, very cool dashboard :)

**Comment by rubenfiszel** [comment]
Awesome!

Thank you :)

Ruben Fiszel

2016-08-17 16:12 GMT-07:00 Marek Wydmuch <notifications@github.com>:

**Comment by ebonyclock** [comment]
@rubenfiszel 
https://github.com/Marqt/ViZDoom/commit/1664c83731f1a4e62a5ddcc70fc00c618a1cdbab <- this commit should let you catch ViZDoom<WHATEVER>Exception 

Were you successful in finding the reason for the crash itself?

**Comment by rubenfiszel** [comment]
I wasn't able to reproduce yet which lead me to believe that it was an OOM indeed. Thanks for the commit and the great project :)

**Comment by LinZichuan** [comment]
Hi @Marqt , I run `python basic.py` on Ubuntu 14.04 LTS server(I login by `ssh -X`), but came out an error.
```
*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x10

Generating vizdoom-crash.log and killing process 1324, please wait... 40	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
Traceback (most recent call last):
  File "basic.py", line 97, in <module>
    game.init()
vizdoom.ViZDoomErrorException: Unexpected ViZDoom instance crash.
```
What should I do to solve this problem?

**Comment by Marqt** [comment]
Hi @LinZichuan, could you post vizdoom-crash.log?

**Comment by LinZichuan** [comment]
OK @Marqt , thanks for your reply, the crash log file is below.
[vizdoom-crash.log.txt](https://github.com/Marqt/ViZDoom/files/608861/vizdoom-crash.log.txt)

**Comment by fuxianh** [comment]
@LinZichuan  I get into the same trouble like you, do you have any suggestion now?

**Comment by LinZichuan** [comment]
@fuxianh  I reinstalled NVIDIA driver and this problem was solved. https://davidsanwald.github.io/2016/11/13/building-tensorflow-with-gpu-support.html

**Comment by fuxianh** [comment]
My server is Ubuntu 14.04, cuda version is V7.5.17, I noticed in the link you give to me, the cuda version is 8.0, is it because of the cuda version is low? Thank you for your nice answer.
