### ISSUE TITLE
Use with OpenMP

### ISSUE THREAD

**Issue by dementrock** [Marqt/ViZDoom#113]
Can ViZDoom be used with OpenMP? Are there any possible race conditions that need to be guarded?

**Comment by Marqt** [comment]
DoomGame's methods aren't thread safe, `makeAction`, `advanceAction`, `setAction` should be guarded.

**Comment by dementrock** [comment]
@Marqt What if different threads are using different DoomGame instances? I didn't find any global references in these methods.

**Comment by wjaskowski** [comment]
It works.

**Comment by dementrock** [comment]
@wjaskowski Thanks!
