### ISSUE TITLE
Load new scenario without recreating DoomGame

### ISSUE THREAD

**Issue by dementrock** [Marqt/ViZDoom#114]
Is this possible? Recreating DoomGame seems pretty heavy compared to restarting a new episode.... If there's no such functionality yet, how hard would it be to support this, and would there be a noticeable performance gain compared to simply relaunching the processes?

**Comment by Marqt** [comment]
Unfortunately ZDoom engine doesn't support the loading of new .wad files during runtime and looks like that adding this would require quite a bit of work. Engine starts really fast so I think this is not a big deal. Also `setMap` can be used in any moment and works almost immediately. So if you would like to switch scenarios without restarting engine create .wad file with more then one map. Slade editor let you copy maps from one file to another one.

**Comment by dementrock** [comment]
Thanks @Marqt! My use case is that I want each episode to use a randomly generated new map, and the simulation time is dominated by the engine start time when each episode is short. Do you think if instead of loading new .wad files, it would be possible to dynamically adding new maps to an already loaded wad file?

**Comment by Marqt** [comment]
ZDoom indexes all resources in the wad files at start. So it rather won't recognize a new map after init. It seems that it also loads into memory full map definitions and scripts. Replacing wad file during runtime, with one with different map also doesn't work. At this moment the best approach will be to use wads with large number of maps.

Actually, I read today about OBLIGE - level generator for Doom and I was thinking about exactly the same thing. May I ask how you will be generating these maps?

I will look deeper into code that loads wads' data and try to figure out something, but it probably will take some time.

**Comment by dementrock** [comment]
Thanks for looking into this! Right now I am generating these maps by directly writing binary WAD files, which is not that ideal...

**Comment by Marqt** [comment]
I've just found a trick implemented in ZDoom engine that allows you to load single map from file during runtime, so now setDoomScenarioPath allows to do that.

```
game.set_doom_scenario_path("path to new .wad file")
game.new_episode()
```
