### ISSUE TITLE
[lua binding] how to convert state.screenBuffer to torch.Tensor?

### ISSUE THREAD

**Issue by pengsun** [Marqt/ViZDoom#120]
I've successfully played around with the lua binding in master branch, just a simple question: 

Take `examples/lua/basic.lua` for instance, how to convert `state.screenBuffer` [at this line](https://github.com/Marqt/ViZDoom/blob/master/examples/lua/basic.lua#L117) to `Torch.Tensor` (let's presume lua binding users are simultaneously Torch 7 users...)? 

I also tried `lua_alt` with the author's personal fork. It works pretty well and the returned state variables come with `torch.Tensor`, but unfortunately some fields are missing (e.g., `state.depthBuffer`).

**Comment by Marqt** [comment]
At the moment buffers' data are kept as Lua userdata and can be copied to tensor:

```
screenBuf = torch.ByteTensor(3, 480, 640)
ffi.copy(screenBuf:data(), state.screenBuffer, 3 * 480 * 640)
```

We will change it soon.

**Comment by pengsun** [comment]
@Marqt thanks for your quick reply!! BTW, what's your near plan? Returning `torch.Tensor` directly?

**Comment by Marqt** [comment]
Yes, I think it will be the best option. Still not sure about the action format - keep it as Lua table or change to tensor? Any suggestions?

**Comment by pengsun** [comment]
Hmm... Just realized the current lua binding does not depend on Torch at all (it only depends on native lua, right?), so it would be a good idea to keep this "clean version" as is. After all, it is quite easy to convert buffer data (as you showed above) or lua table to `torch.Tensor` (something like `torch.Tensor{1, 0, 0}`) in pure lua end. 

However, if you've decided to do everything in Torch, then both the state fields and the actions would better be `torch.Tensor` for consistency reason.

Just personal thoughts...

**Comment by pengsun** [comment]
Hi @Marqt, there is trivial flaw in your examplar code -- the dimension order and RGB order are problematic. The correct code should look like
``` lua
ffi = require'ffi'
require'image'

screenBuf = torch.ByteTensor(3*480*640)
ffi.copy(screenBuf:data(), state.screenBuffer, 3*480*640)

screenBuf:vew(480, 640, 3)
    :permute(3, 1, 2)
    :index(1, torch.LongTensor{3, 2, 1})

image.display(screenBuf)
```  

as [these lines of code](https://github.com/Marqt/ViZDoom/blob/master/src/lib_lua_alt/ViZDoomLua.lua#L86-L92)

**Comment by Marqt** [comment]
Sorry for the late replay.

We have different buffers format. The most useful are CRCGCB and GRAY8 (in basic example RGB24 is set in setScreenFormat to show the method).

For these formats, code I wrote is all You need.

**Comment by pengsun** [comment]
Oh, didn't notice that... Thanks for pointing it out!

**Comment by Marqt** [comment]
I've added wrapping layer to lua binding that handles userdata to torch.Tensor conversion. So I'm closing this one. Thank you @pengsun for suggestions.
