### ISSUE TITLE
when the sound buffer will be available in the API ?

### ISSUE THREAD

**Issue by ChelaruViorel** [Marqt/ViZDoom#121]
In the ViZDoom paper
https://arxiv.org/pdf/1605.02097.pdf
at the conclusions, there is this statement : Second, bots are now deaf thus, we plan
to allow bots to access the sound buffer.

Can you tell me a date or a month this year or in 2017, when the sound buffer will be available ? Doesn't have to be an exact date.

**Comment by wjaskowski** [comment]
We not working on this at the moment and have no specific schedule for this
idea. I do not know how many people actually would make use of it.


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by ChelaruViorel** [comment]
I would want to use it, so it's 1 for the moment. 
Thanks for answering.
Viorel
