### ISSUE TITLE
Absolute paths resolution in configs does not work with symbolic links

### ISSUE THREAD

**Issue by wjaskowski** [Marqt/ViZDoom#122]
e.g. when accessing basic.cfg which is in config, where config is a symbolic link not a real directory

**Comment by ebonyclock** [comment]
Could you write how to reproduce it?
I had the following structure and everything works ok:
-some_directory
----\config
    ----\basic.wad
    ----\basic.cfg
-current_dir
---test.py
---config->some_directory/config

**Comment by wjaskowski** [comment]
-some_directory
--\config
---\basic.cfg
--\wads
---\doom2.wad
-current_dir
---test.py
---config->../some_directory/config

basic.cfg contains:
```doom_game_path = ../wads/doom2.wad```

If basic.cfg is a copy in current_dir it works. If it linked then I get:
```Vizdoom.FileDoesNotExistException: File "config/../../wads/doom2.wad" does not exist.```
