### ISSUE TITLE
Support for Boost 1.61

### ISSUE THREAD

**Issue by danijar** [Marqt/ViZDoom#124]
The installation looks for `libboost_filesystem.so.1.60.0`. This breaks on Arch Linux where boost 1.61 is the default.

```
  File "/usr/lib/python3.5/site-packages/doom_py/__init__.py", line 1, in <module>
    from doom_py.vizdoom import *
ImportError: libboost_filesystem.so.1.60.0: cannot open shared object file: No such file or directory
```

**Comment by ppwwyyxx** [comment]
Maybe you just need to recompile vizdoom after upgrading boost. Works fine with me.

**Comment by ebonyclock** [comment]
@danijar Just like @ppwwyyxx wrote, most likely you compiled against boost 1.60.0, try to recompile/reinstall it. By the way doom_py is really outdated, soon vizdoom will be pip installable on its own (see pip_dev branch for details or contributions).

**Comment by danijar** [comment]
@ebonyclock Do you think its an issue with doom_py then? Because I reinstalled a couple of times, but I'll see if it cached the builds somewhere. I'd like to use the gym wrappers.

**Comment by ebonyclock** [comment]
@danijar doom_py should work with whatever version of Boost you have so I wouldn't call it an issue. You are right that if pip somehow cached the build it would misbehave after  boost's version change.

**Comment by ebonyclock** [comment]
@danijar To be sure I have tested doom_py on my system and it turned out that I have installed it when I had boost 1.61 and now it gave me the exact error that you had (but with 1.61). ''pip install doom_py --upgrade' didn't work but everything is ok after pip uninstall and install.

**Comment by wjaskowski** [comment]
Did you cmake_clean.sh before make?


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by ebonyclock** [comment]
@danijar Does it work ok now?

**Comment by danijar** [comment]
Uninstall and reinstall works for me as well, thanks!
