### ISSUE TITLE
[lua binding] Unable to make with lua binding option

### ISSUE THREAD

**Issue by sdharashivka** [Marqt/ViZDoom#125]
Hi,
I am using ubuntu16.04 . I have installed Lua 5.1.5. I also have libluabind-dev package. 
When I try to make, I get the following error:

make[2]: **\* No rule to make target 'src/lib_lua/luabind/src/libluabind.a', needed by 'bin/lua/vizdoom.so'.  Stop.
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/libvizdoom_lua.dir/all' failed
make[1]: **\* [CMakeFiles/libvizdoom_lua.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: **\* [all] Error 2

This may be trivial issue. But I am a new user of Lua and I will be grateful if you can send me this information.

**Comment by Marqt** [comment]
Hi, sorry for late replay.
Could you use cmake_clean.sh then use cmake command again and post its output?

**Comment by sdharashivka** [comment]
Hi,
After using cmake_clean.sh, I used the cmake again. The output is as follows:

sachin@sachin-Inspiron-N5050:~/ViZDoom$ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=ON -DBUILD_LUA=ON
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   thread
--   system
--   date_time
--   chrono
--   regex
--   iostreams
--   atomic
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found JPEG: /home/sachin/anaconda2/lib/libjpeg.so  
-- Found ZLIB: /home/sachin/anaconda2/lib/libz.so (found version "1.2.8") 
-- Could NOT find GME (missing:  GME_INCLUDE_DIR) 
-- Using system zlib
-- Using system jpeg library
-- Using system bzip2 library
-- Using internal gme library
-- Performing Test HAVE_NO_ARRAY_BOUNDS
-- Performing Test HAVE_NO_ARRAY_BOUNDS - Success
-- Performing Test __LIBGME_TEST_VISIBILITY
-- Performing Test __LIBGME_TEST_VISIBILITY - Success
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of char
-- Check size of char - done
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- /home/sachin/anaconda2/include
-- /usr/include
-- /home/sachin/ViZDoom/src/vizdoom/lzma/C
-- Looking for itoa
-- Looking for itoa - not found
-- Performing Test DUMB_CAN_USE_SSE
-- Performing Test DUMB_CAN_USE_SSE - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.30
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Could not find FMOD include files
-- Could NOT find SndFile (missing:  SNDFILE_LIBRARY SNDFILE_INCLUDE_DIR) 
-- Could NOT find MPG123 (missing:  MPG123_LIBRARIES MPG123_INCLUDE_DIR) 
-- Found FluidSynth: /usr/lib/x86_64-linux-gnu/libfluidsynth.so  
-- Selected assembler: /usr/bin/as
-- Looking for filelength
-- Looking for filelength - not found
-- Looking for strupr
-- Looking for strupr - not found
-- Looking for stricmp
-- Looking for stricmp - not found
-- Looking for strnicmp
-- Looking for strnicmp - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Performing Test HAS_VA_COPY
-- Performing Test HAS_VA_COPY - Success
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   date_time
--   chrono
--   atomic
-- Fluid synth libs: /usr/lib/x86_64-linux-gnu/libfluidsynth.so
-- Found PythonInterp: /home/sachin/anaconda2/bin/python2 (found suitable version "2.7.12", minimum required is "2") 
-- Found PythonLibs: /home/sachin/anaconda2/lib/libpython2.7.so (found suitable version "2.7.12", minimum required is "2.7") 
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python
-- Found NUMPY: /home/sachin/.local/lib/python2.7/site-packages/numpy/core/include  
-- Found components for NumPy
-- NUMPY_ROOT_DIR    = /usr/local
-- NUMPY_INCLUDES    = /home/sachin/.local/lib/python2.7/site-packages/numpy/core/include
-- NUMPY_LIBRARIES   = 
-- NUMPY_API_VERSION = 1.11.2
-- Configuring luabind in release mode
-- Disabling unit tests
-- Found Lua51: /usr/lib/x86_64-linux-gnu/liblua5.1.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.1.4") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sachin/ViZDoom

I am able to make with the Python binding.

**Comment by Marqt** [comment]
Fixed, thank you @sdharashivka!
Remove CMakeCache.txt and use cmake command again.

**Comment by sdharashivka** [comment]
Thanks a lot, @Marqt

**Comment by Marqt** [comment]
And I'm sorry @sdharashivka that it took so long.
