### ISSUE TITLE
Network play out of sync

### ISSUE THREAD

**Issue by yuandong-tian** [Marqt/ViZDoom#126]
I met with an issue when running cig.py and cig_host.py in example/python, on scenarios/multi_deathmatch.wad. The two programs are supposed to connect to each other and play a game. They apparently connect and show the visualization from each player's perspective. However, it turns out that the two game played by cig.py and by cig_host.py are not the same (Image attached below, one player can see the other but not the other way round). Also, from visualization, we could see "out of sync". 

How to solve this? Thanks!

![image](https://cloud.githubusercontent.com/assets/2973937/19738783/86be3602-9b6d-11e6-8c04-9188456ff664.png)

**Comment by ebonyclock** [comment]
It also happens on cig scenario and it wasn't like that. I am affraid it could be a bug, we'll see into this.

**Comment by yuandong-tian** [comment]
This bug does not appear until the following commit:
https://github.com/Marqt/ViZDoom/commit/7bfcce2ce6ac2be32bc2c72fc647ecb1ae3914d7

**Comment by Marqt** [comment]
Fixed, thanks @yuandong-tian
