### ISSUE TITLE
luabind error

### ISSUE THREAD

**Issue by pengsun** [Marqt/ViZDoom#129]
Hi,

after the new commits 0de20a6d9d53d6aa83084e72bd509622f85bd079, an error
```
lua: /home/xxx/ViZDoom/src/lib_lua/luabind/src/class_registry.cpp:126: void luabind::detail::class_registry::add_class(const luabind::type_id&, luabind::detail::class_rep*): Assertion `(m_classes.find(info) == m_classes.end()) && "you are trying to register a class twice"' failed.
Aborted (core dumped)
```
raised when running any lua script in `examples/lua`. Could you take a look?

BTW, the luabind doesn't compile with current cmake, one must cmake luabind separately to get `libluabind.a`.

**Comment by Marqt** [comment]
Looks like it's connected with #125.

At the moment I can't replicate this. I've tried on Ubuntu 16.04 with gcc-4.8, 5 and 6. Building luabind and examples works fine for me.

Could you post more informations about your environment?

**Comment by pengsun** [comment]
Yes, the problem has gone.
