### ISSUE TITLE
python 3.4 binaries for windows?

### ISSUE THREAD

**Issue by imrodriguezro** [Marqt/ViZDoom#132]
I tried to compile the project from the sources, but it's just a pain in the neck. Are you planning to provide a python 3.4 library soon? Thanks!

**Comment by Marqt** [comment]
We are recently pretty busy with other things but a new release is just around the corner (and new binaries for Windows including Python 2.7, 3.4, 3.5 with it). Personally, I would like to finish it this week.

**Comment by imrodriguezro** [comment]
Thanks for your quick answer! Then I'll wait patiently :)

**Comment by Marqt** [comment]
I'm sorry to have kept you waiting, it took much more time than I thought, but new release with new binaries is finally here.

**Comment by imrodriguezro** [comment]
Thank you!
