### ISSUE TITLE
Disable bodies? 

### ISSUE THREAD

**Issue by ppwwyyxx** [Marqt/ViZDoom#136]
Is there any way (a pointer to modifying the source code is OK) to not display dead bodies in game?

Too many bodies can be a concern point to people worrying about killer AIs.

**Comment by ebonyclock** [comment]
Yes, it's doable via acs scripting (in the scenario). I am not sure if it can be done more easily but we handle it by removing the object (monster) after its death. It's done in e.g. defend the center scenario - it's done with SetThingSpecial and Thing_Remove (in Script 3).

**Comment by ppwwyyxx** [comment]
Thanks! Is there ways remove bodies of other players?

**Comment by Marqt** [comment]
Hi, 
I've just added function `setRenderCorpses/set_render_corpses` - it does what the name implies, works also for players' bodies in multi.

**Comment by ppwwyyxx** [comment]
Thanks so much for the quick response!
