### ISSUE TITLE
AttributeError: 'DoomGame' object has no attribute 'set_depth_buffer_enabled'

### ISSUE THREAD

**Issue by MyOwnClone** [Marqt/ViZDoom#137]
Hi, I am using windows prebuilt version 1.0.4 and after launching python basic.py I got:

```
> python basic.py
Traceback (most recent call last):
  File "basic.py", line 50, in <module>
    game.set_depth_buffer_enabled(True)
AttributeError: 'DoomGame' object has no attribute 'set_depth_buffer_enabled'
```

I believe that this is an error and this should not happen.

I am using Windows 10 x64 a Python, version 2.7.12.
Little side note: documentation for Windows should mention that you need to use x64 python version, I've struggled with it, until I found out.

**Comment by Marqt** [comment]
Hi,

'set_depth_buffer_enabled' is method that we added recently in 1.1 version.

To find out how to access a depth buffer in 1.0.4 see this example from 1.0 branch: https://github.com/Marqt/ViZDoom/blob/1.0/examples/python/format.py

But I'm preparing new windows binaries, they will be available tomorrow so you may want to wait.

Also, sorry for your struggle with python versions, I thought that the x86-64 in the archive's name is enough to make it clear.

**Comment by MyOwnClone** [comment]
Hi, thanks for the info! I've managed to build Windows binaries myself (only having problem with Java bindings) and ```set_depth_buffer_enabled``` works fine there. But this is due to the fact, that I've built from newest sources.

**Comment by Marqt** [comment]
We've made new release and added new binaries so I'm closing this.
