### ISSUE TITLE
vizdoom (shared object most probably) is not found on mac and windows.

### ISSUE THREAD

**Issue by ebonyclock** [Marqt/ViZDoom#147]
On some macs  path to vizdoom cannot be found on init:
vizdoom.vizdoom.FileDoesNotExistException: File "vizdoom" does not exist.

On Windows it's not even implemented.

**Comment by TGlas** [comment]
I had to redirect the link to `ViZDoom/bin/vizdoom.app/Contents/MacOS/vizdoom` in order to make this work on my Mac.
