### ISSUE TITLE
Lua not found on ubuntu install

### ISSUE THREAD

**Issue by culurciello** [Marqt/ViZDoom#150]
Hi Guys, lua LIBS are not found on my Ubuntu box 16.04, see:
[lua-ubuntu-not-found.txt](https://github.com/Marqt/ViZDoom/files/636971/lua-ubuntu-not-found.txt)

I am debugging it..

**Comment by Marqt** [comment]
Have you installed lua dev package? (`apt-get install liblua5.1-dev)`.

**Comment by culurciello** [comment]
thank you that was the problem, thanks!
