### ISSUE TITLE
What does get_state().number mean ?

### ISSUE THREAD

**Issue by tabsun** [Marqt/ViZDoom#154]
The return of get_state() contains game_variables, image_buffer and number. The first two are easy to comprehend, but what's the number? 
Thanks

**Comment by ebonyclock** [comment]
It's just an ordinal number of the state. Basically it's incremented every time you call make_action (starting from 1 for the initial state).

**Comment by wjaskowski** [comment]
Should be named "tick", probably.


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by tabsun** [comment]
OK, I got it. Thanks for @ebonyclock and @wjaskowski
