### ISSUE TITLE
Count or detect monsters on screen

### ISSUE THREAD

**Issue by pavitrakumar78** [Marqt/ViZDoom#163]
Hi,

I was wondering if it is possible to check whether there is a monster on screen currently.
I know I can try to use image processing techniques, but is there an internal game variable which tells us whether there is a monster on screen or give a count of monsters currently on the player's screen (the doom guy's FOV)?

**Comment by Marqt** [comment]
It is, ViZDoom have a tool for that. See labels.py/lua example.

**Comment by pavitrakumar78** [comment]
Just what I wanted! Thank you!
