### ISSUE TITLE
respawnPlayer may couse incorrect end of the multiplayer game when called in few last tics

### ISSUE THREAD

**Issue by Marqt** [Marqt/ViZDoom#166]
...which causes map change and leads to further errors.

Reported by @pengsun - thank you.

**Comment by Marqt** [comment]
I haven't found the exact cause of it yet. But this should prevent it from occurring.

**Comment by pengsun** [comment]
Wow, amazing! You are so efficient, thank YOU!

**Comment by Marqt** [comment]
I've run few thousand episodes with random agent (30 seconds each) without a problem so I assume that the fix works and I'm closing it.
