### ISSUE TITLE
game becomes slow

### ISSUE THREAD

**Issue by glample** [Marqt/ViZDoom#171]
I observed that the game becomes slower and slower as it goes on. Typically, at the beginning of training, my code runs at 400 iterations in 6 seconds. 30 minutes later, it is about 7 or 8 times slower. Every 30 minutes I close the game and create a new DoomGame object. Then training goes back to its original speed of 6 seconds for 400 iterations. And then it progressively becomes slow again, etc.

So it looks like there is something wrong, maybe a memory leak or something.
Notes:
- I'm using python
- this only happen when I put "-host 1" in the arguments. When I don't put that, speed remains constant (but the game is reset at each death, and I don't want that)

**Comment by glample** [comment]
The issue seems to appear when `game.respawn_player()` is called.

Adding `game.add_game_args("-host 1")` to the example `fps.py` also makes the FPS rate 10x slower.

**Comment by Marqt** [comment]
Hmm, that's interesting.
Personally I can't observe any slow down on Ubuntu using Python 2.7. 
I've tested:
- 30 minutes of singleplayer scenario with/without `-host 1`
 argument - same stable fps
- 30 minutes of deathmatch with 7 bots (with/without additional buffers)- stable fps through the whole game 

Also I don't see any memory leak. Did you observed any?
Could you tell me more about your environment? System? Python and ViZDoom version? Are you using Python threads/processes - if yes, maybe you can share with us a chunk of code which allows to reproduce the issue?

**Comment by glample** [comment]
Hello,

I'm really sorry, I realized the bug was from my side... It was a very specific bug. The problem was that I had an error in my ACS code which was executed at each respawn, so without "-host 1" the bug was not visible because the game was reset at each death, and the buggy code was never called.

Anyway, sorry about that!

**Comment by Marqt** [comment]
No problem, thanks for letting us know.
