### ISSUE TITLE
DoomGame.init() crash on the Korean (and probably Japanese) Windows

### ISSUE THREAD

**Issue by rex8312** [Marqt/ViZDoom#28]
I have try prebuild version for windows.
But it's not work for me. 

I have tried python examples and all examples print out same error message.
The Error message is 
"This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."

It print when executing "game.init()".

**Comment by wjaskowski** [comment]
What version of Windows do you use?


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by Marqt** [comment]
Hello, 
is the full error message looks like this:
`File "basic.py", line 78, in <module>
    game.init()
vizdoom.path_does_not_exist_exception: Path "../../bin/vizdoom" does not exists.

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.`?

Or is it only:
`This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.`?

In the first case:
Currently examples and config files need little fix to work on Windows - extension ".exe" must be added to vizdoom_path. Examples assume vizdoom executable is located in the <vizdoom_root_dir>/bin directory. 

If there is no information about the exception, run vizdoom.exe separately, it should return more specific information about error.
We tested ViZDoom on Windows 7 and Windows 8.1. Are You using Windows 10?

**Comment by rex8312** [comment]
I have tested Windows 8.1 64 bit and 10 64 bit.
I already change directory structure to remove path relevant error messages.
So there are only this error message

```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

ViZDoom work well if I execute vizdoom.exe except sound.
There are only error message about sound. 
```
sound init faild: using nosound
..
starting midi playback failed
```

So. I can play doom myself with no sound.

**Comment by rex8312** [comment]
![error](https://cloud.githubusercontent.com/assets/3638075/14404816/5672b87e-feba-11e5-98bf-76046daa9de5.png)

There are error message box also.
Messages: "python.exe is stopped, because there are problem occur"
Buttons: "Debug" and "Close program"

**Comment by Marqt** [comment]
Do You use ₩ in any ViZDoom's paths? It seems a very likely cause of the problem. 
ViZDoom's paths correctly supports only 8-bit characters. 
If this is the case, for now use \ instead of ₩, we fix it and add support for ¥ and ₩ as folder separators.

**Comment by rex8312** [comment]
I didn't modify example code, so It use '/' as forder separator. not '₩' or '\'.

If I use '\' then ..
![error2](https://cloud.githubusercontent.com/assets/3638075/14406045/62f61406-fed8-11e5-86c6-9409b8da4c0c.png)
Even there are no error dialogue. Maybe this is the real path problem.
In Korean windows '₩₩', '\\' is same to '/', single '\' is not working.

Also, I have copy all contents of vizdoom to single folder to delete folder separator in basic.py.
But, It is still not working.

**Comment by Marqt** [comment]
Yes, it can also be the real path problem, it is very likely used by boost::process. 

I will prepare tomorrow debug version of vizdoom.pyd for You to get us some details about that and other possible causes.

**Comment by rex8312** [comment]
I found reason for this.

I am misunderstand `vizdoom` as folder name not file name in `"game.set_vizdoom_path("../../bin/vizdoom")".`
after I add file extention (exe), It works well.
```
"game.set_vizdoom_path("../../bin/vizdoom")". 
--> "game.set_vizdoom_path("../../bin/vizdoom.exe")".
```

So problem solved, Thanks for your efforts.

**Comment by Marqt** [comment]
I have just prepared a new build that includes a few bug fixes (including that one) and improvements of the Windows version (and makes examples work out of the box), so I encourage You to clone our repo again and download version 1.0.0.
