### ISSUE TITLE
Lua binding

### ISSUE THREAD

**Issue by ebonyclock** [Marqt/ViZDoom#32]

**Comment by glample** [comment]
Hello.
Any progress on this?

**Comment by Marqt** [comment]
Sorry, I haven't had time recently to develop ViZDoom and I was hoping that because ViZDoom has a very small api someone more experience with Lua and Torch will make these binding. But since no one did, I started to work on it yesterday. I need to get into Lua and Torch, so give me a few more days.

**Comment by glample** [comment]
Hey,

It looks like almost everything is done in the dev branch. What is left to do?

**Comment by ebonyclock** [comment]
As mentioned by @glample done in 1.1-dev, soon in master.
