### ISSUE TITLE
consider linking to doomwiki.org instead

### ISSUE THREAD

**Issue by jmtd** [Marqt/ViZDoom#35]
Hey there, [the competition page](http://www.cs.put.poznan.pl/visualdoomai/competition-cig-2016.html) links to a Doom Wiki hosted at Wikia.com.  Some time ago, the original administrators and contributors to that wiki decided to leave and formed [doomwiki.org](http://doomwiki.org) instead. The wiki forked at that point and the original Wikia was largely abandoned ([more about the fork here](http://doomwiki.org/wiki/Doom_Wiki:Departure_from_Wikia)). Some might argue that the content on doomwiki.org is now considerably more developed and up-to-date. I just wanted to see whether you would consider linking to there instead. Thanks for your consideration.

**Comment by wjaskowski** [comment]
Thanks. I was not aware that. Fixed.
