### ISSUE TITLE
WSAD controls

### ISSUE THREAD

**Issue by shelpuk** [Marqt/ViZDoom#38]
Is there a way to enable WSAD controls instead of arrows?

**Comment by Marqt** [comment]
Yes, when Your program call init() method, `vizdoom.ini` will be created in program dir. It will contain the default ZDoom engine's settings. Find `[Doom.Bindings]` and change them as You like.

```
w=+forward
a=+left
d=+right
s=+back
```

**Comment by shelpuk** [comment]
Are there just these four controls? Is there a way I can assign strafe left and strafe right to A and D?

**Comment by Marqt** [comment]
Moveleft and moveright are for strafing, left and right for turning.

**Comment by shelpuk** [comment]
Thanks a lot!
