### ISSUE TITLE
Enabling Sound

### ISSUE THREAD

**Issue by yankov** [Marqt/ViZDoom#40]
Is there a way to enable sound? It is not needed during the training but very nice to have during the demos.

**Comment by Marqt** [comment]
You are totally right! 
I have just added a function `setSoundEnabled(bool)` (`set_sound_enabled(bool)` in Python). 

Note that in sync modes music playback may not be continuous (depending on the processing speed).

**Comment by yankov** [comment]
sweet, thank you!
