### ISSUE TITLE
Access to depth buffer

### ISSUE THREAD

**Issue by shelpuk** [Marqt/ViZDoom#41]
Didn't find that in docs... How can I get depth buffer out of the state?

**Comment by wjaskowski** [comment]
game.set_screen_format(ScreenFormat.DEPTH_BUFFER8)

See the format.py example.

Note however that the access to the depth buffer is disallowed for the CIG
competition by the "+vizdoom_nocheat 1" option (see cig_host.py).


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by ebonyclock** [comment]
You could also use two formats that smuggle Zbuffer with the ordinary screen buffer:
ScreenFormat.CRCGCBDB
ScreenFormat.CBCGCRDB.

**Comment by shelpuk** [comment]
Is there a way I can get depth buffer along with the image? When I do:
game.set_screen_format(ScreenFormat.DEPTH_BUFFER8
I am getting depth buffer in image_buffer which makes sense. But how can I get both, a normal game screen and a corresponding depth buffer?

**Comment by Marqt** [comment]
Use those mentioned `ScreenFormat.CRCGCBDB` or `ScreenFormat.CBCGCRDB` (it stands for: CR - channel red + CG - channel green + CB - channel blue + DB - depth buffer).
So it will give You 3 channels of RGB or BGR image and depth buffer on fourth channel.

**Comment by ebonyclock** [comment]
I thought C stands for consecutive XD...

**Comment by GoingMyWay** [comment]
You can try

```
import matplotlib.pyplot as plt

# Enables depth buffer.
game.set_depth_buffer_enabled(True)
depth = state.depth_buffer
plt.imshow(depth)
plt.show()
```
