### ISSUE TITLE
Upper limit on FPS

### ISSUE THREAD

**Issue by shelpuk** [Marqt/ViZDoom#43]
Is there a way to set upper limit on FPS?

**Comment by shelpuk** [comment]
If not, just a way to get the exact FPS number would work too.

**Comment by ebonyclock** [comment]
Generally no, but if it's for watching purpose you could just use sleep or some other delay functions.

**Comment by shelpuk** [comment]
Ok, thanks, maybe there is a way I can get the exact number for the episode?

**Comment by ebonyclock** [comment]
No. In asynchronous mode ispeed is fixed at 35 fps and that's it.

**Comment by shelpuk** [comment]
I mean, is there any function which can return me current FPS for the game?

**Comment by wjaskowski** [comment]
There is no such function. In async mode the FPS is constant = 35 and
currently cannot be changed. In sync mode, it is you who is has the full
control and you can compute it yourself in some time window.


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by shelpuk** [comment]
Ok, thanks.
