### ISSUE TITLE
AttributeError: 'DoomGame' object has no attribute 'set_doom_engine_path'

### ISSUE THREAD

**Issue by shelpuk** [Marqt/ViZDoom#48]
I am configuring the game according to the tutorial:
http://vizdoom.cs.put.edu.pl/tutorial#basic
```
from vizdoom import *
...
game = DoomGame()
...
game.set_doom_engine_path("../../bin/vizdoom")
```

The interpreter returns:
`AttributeError: 'DoomGame' object has no attribute 'set_doom_engine_path'`

What do I do wrong?

**Comment by ebonyclock** [comment]
Nothing. "set_doom_engine_path" was the old version and we forgot to change it in the tutorial, sorry. It should be "set_vizdoom_path".
