### ISSUE TITLE
Unexpected jumping behavior when running `cig_host.py`

### ISSUE THREAD

**Issue by tomlepaine** [Marqt/ViZDoom#52]
I just installed `ViZDoom` on my mac os laptop. I can run `bin/vizdoom` without any strange behavior, but when I run `examples/python/cig_host.py` and `cig.py` the player controlled by the host script jumps and moves uncontrollably. The player controlled by `cig.py` works just fine.

I cannot recreate this behavior on my linux machine.

Also, I can fix this behavior by fiddling with:

`game.add_game_args()`, but it seems to be more related to the number of flags, than the flags themselves... This is very puzzling to me.

Any ideas what is going on?

**Comment by wjaskowski** [comment]
At the moment, I can only confirm this strange behavior on OSX. The bot
should not jump at all, in the first place. It also behaves similarly in
ASYNC_SPECTATOR mode as if some buttons were constantly pressed.

I also confirm that the problem disappears when only 4 commands (in total,
independent on the number of calls) are added via the add_game_args(). 5th
command (even a repeated one) causes troubles.


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by ebonyclock** [comment]
It'll be hard to check without macs... Anyway maybe something went  wrong with key mappings somehow. Could you try making this  'game.make_action([0])' to check if being idle also results in this crazy jumping?

**Comment by wjaskowski** [comment]
On 3 May 2016 at 12:11, Michał Kempka <notifications@github.com> wrote:

> It'll be hard to check without macs... Anyway maybe something went wrong
> with key mappings somehow. Could you try making this
> 'game.make_action([0])' to check if being idle also results in this crazy
> jumping?
>
Yes it does.

**Comment by tomlepaine** [comment]
Great. I'm glad it is not just my machine 😺. If there is anything I can do to help let me know.

**Comment by dwhit** [comment]
I have the same bug on my mac. not sure the cause.

**Comment by wjaskowski** [comment]
This problem has disappeared, quite unexpectedly.

**Comment by devendrachaplot** [comment]
I started having this problem two weeks ago. Any idea what triggers this bug?

**Comment by ebonyclock** [comment]
Not really, w don't generally use macs so it was hard to find it and then ...it disappeared after some commit. I assume that you are using an up-to-date version and the bug is back :(?

**Comment by Marqt** [comment]
@devendrachaplot Which version/commit are you using? Has the bug started occurring after pull/version update?

**Comment by devendrachaplot** [comment]
I am using the latest version. Yeah, it has occurred even after I pulled the latest version. Its specifically occurring in cig_bots.py

**Comment by wjaskowski** [comment]
I cannot confirm it at the moment because my mac is broken but I was pretty
sure that this problem has stopped occurring some time ago.
