### ISSUE TITLE
ImportError: No module named site

### ISSUE THREAD

**Issue by LinxiFan** [Marqt/ViZDoom#53]
I compiled ViZDoom with Enthought python 2.7 on Mac OS X. 

When I try to run the example `basic.py`, I get `ImportErrror: No module named site`. StackOverflow suggests it's a pythonpath problem, but I can't figure out how to fix it. Thanks!

**Comment by ebonyclock** [comment]
Is your python installed correctly? Do you get the errer when you run just python not our examples specifically?

**Comment by LinxiFan** [comment]
It looks like an Enthought problem. I switch to another python installation and it works.
