### ISSUE TITLE
Spectator mode + PrintScreen interfere with other buttons

### ISSUE THREAD

**Issue by ebonyclock** [Marqt/ViZDoom#54]
When I press print screen while unclicking other buttons (arrows, wsad, ctrl etc) the unclicking is ignored. I don't know if it interferes with other buttons than printscreen.

**Comment by Marqt** [comment]
Do You think it is a ViZDoom's bug? I can't replicate it and I think that it's rather related with fact that when You press printscreen, ViZDoom window is loosing focus.

**Comment by Marqt** [comment]
I don't think it is related to the engine, rather with SDL, xserver, gui environment - closing.
