### ISSUE TITLE
Compilation (execution?) changes some files

### ISSUE THREAD

**Issue by wjaskowski** [Marqt/ViZDoom#57]
i.e., 

``examples/python/bots.cfg``, where it reads "/home/marek/Workspace/ViZDoom/examples/config/bots.cfg".

and 

``src/vizdoom/src/xlat_parser.out``

Do we need those files in repo at all?

**Comment by ebonyclock** [comment]
"src/vizdoom/src/xlat_parser.out" was added to .gitignore and removed.

"examples/python/bots.cfg" should not be in the repostitory, i'll delete and blacklist it.

**Comment by Marqt** [comment]
I've forgot to update `.gitignore` after changing dirs structure - that's why "xlat" files leaked into the repo. It looks like that symlink to `bots.cfg` is in repo for a long time and no one noticed it. I've added config files (`*.ini` and `*.cfg`) in `examples/python` to .gitignore
