### ISSUE TITLE
waitpid(2) failed: No child processes

### ISSUE THREAD

**Issue by wjaskowski** [Marqt/ViZDoom#58]
(https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vizdoom/4VEAAxlR2UI/DvytQ9mOCwAJ)

Hi, I just hit an error after > 400k training steps using the health_simple scenario:

```
terminate called after throwing an instance of 'boost::system::system_error'
  what():  in file '/media/homebase/data/Code/ViZDoom/vizdoom_api_src/boost/process/posix/wait_for_exit.hpp', line 30: waitpid(2) failed: No child processes
Aborted (core dumped)
```

What could cause this error and is there a way to get more info on it?

**Comment by ebonyclock** [comment]
It could be caused be vizdoom processs being killed externally. Is there any chance it happened so? E.g. accidental killall.

**Comment by wjaskowski** [comment]
This is minor but we might want to handle such situation with a more
graceful error message if possible

**Comment by oOo0oOo** [comment]
killall is possible but unlikely.. I don't have access to the system right now, but I'll check later.
Ubuntu 14 (14.04.4 LTS if i remember correctly), there was only a single terminal with my code running at the time and no one else has access... Definitely not a shutdown as the system kept running for a few more hours until i discovered the error. In any case this was the first time I ran into this bug and I can work around it (if it even comes up again)...

**Comment by wjaskowski** [comment]
OK. Let me know if it shows up once again.

**Comment by Marqt** [comment]
Message says that core dump was created - could you post it? It would be helpful in determining what went wrong.

**Comment by oOo0oOo** [comment]
Sry for the late reply. This has since not happened and I strongly suspect that it was
related to a bug which lead to GPU memory spiraling out of control; subsequently the system killed the process.

**Comment by Marqt** [comment]
Thank you for info. I will close this one, cause we don't have anything specific to investigate or fix.
