### ISSUE TITLE
Interface to OpenAI Gym

### ISSUE THREAD

**Issue by zdx3578** [Marqt/ViZDoom#59]
will have interface to openai gym?

**Comment by wjaskowski** [comment]
Nice idea! Maybe...


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by ebonyclock** [comment]
It seems that someone added ViZDoom env to OpenAI Gym https://gym.openai.com/envs#doom
