### ISSUE TITLE
Ubuntu build issues w.r.t. boost_chrono

### ISSUE THREAD

**Issue by tycho01** [Marqt/ViZDoom#60]
I'm trying to build ViZDoom on an Ubuntu VM, but I'm getting a build error mentioning Boost's `boost_chrono`:

    vagrant@precise64:/vagrant/python/ViZDoom$ cmake -DCMAKE_BUILD_TYPE=Release -DBU
    ILD_PYTHON=ON -DBUILD_JAVA=ON
    -- Could NOT find JPEG (missing:  JPEG_LIBRARY JPEG_INCLUDE_DIR)
    -- Could NOT find GME (missing:  GME_LIBRARIES GME_INCLUDE_DIR)
    -- Using system zlib
    -- Using internal jpeg library
    -- Using system bzip2 library
    -- Using internal gme library
    -- /usr/include
    -- /usr/include
    -- /vagrant/python/ViZDoom/vizdoom_src/lzma/C
    -- Could NOT find OpenAL (missing:  OPENAL_LIBRARY OPENAL_INCLUDE_DIR)
    -- Could not find FMOD include files
    -- Could NOT find FluidSynth (missing:  FLUIDSYNTH_LIBRARIES FLUIDSYNTH_INCLUDE_DIR)
    -- Selected assembler: /usr/bin/as
    CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1202 (message):
      Unable to find the requested Boost libraries.

      Boost version: 1.46.1

      Boost include path: /usr/include

      The following Boost libraries could not be found:

              boost_chrono

      Some (but not all) of the required Boost libraries were found.  You may
      need to install these additional Boost libraries.  Alternatively, set
      BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
      to the location of Boost.
    Call Stack (most recent call first):
      vizdoom_src/src/CMakeLists.txt:559 (find_package)

    -- Fluid synth libs: FLUIDSYNTH_LIBRARIES-NOTFOUND
    CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1202 (message):
      Unable to find the requested Boost libraries.

      Boost version: 1.46.1

      Boost include path: /usr/include

      The following Boost libraries could not be found:

              boost_chrono

      Some (but not all) of the required Boost libraries were found.  You may
      need to install these additional Boost libraries.  Alternatively, set
      BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
      to the location of Boost.
    Call Stack (most recent call first):
      CMakeLists.txt:56 (find_package)

    -- Found PythonInterp: /usr/bin/python (found suitable version "2.7.3", required is "2.7")
    -- Found PythonInterp: /usr/bin/python (found version "2.7.3")
    -- Could NOT find NUMPY (missing:  NUMPY_INCLUDES)
    CMake Error at CMakeLists.txt:165 (message):
      JAVA_HOME environment variable is not set.

    -- Configuring incomplete, errors occurred!

Installing Boost seemed to have worked without errors though:

    vagrant@precise64:~/boost-build-2016.03$ ./bootstrap.sh   x=/usr
    Bootstrapping the build engine with toolset gcc... engine/bin.linuxx86_64/b2

    Bootstrapping is done. To build and install, run:

        ./b2 install --prefix=<DIR>

    vagrant@precise64:~/boost-build-2016.03$ sudo ./b2 --prefix=/usr/local install
    warning: No toolsets are configured.
    warning: Configuring default toolset "gcc".
    warning: If the default is wrong, your build may not work correctly.
    warning: Use the "toolset=xxxxx" option to override our guess.
    warning: For more configuration options, please consult
    warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
    ...found 613 targets...
    ...updating 2 targets...
    common.copy /usr/local/bin/b2
    common.copy /usr/local/bin/bjam
    ...updated 2 targets...

I'd run into a [similar](http://stackoverflow.com/questions/17279238/boost-chrono-lib-not-being-installed) thread on SO, but it their method doesn't seem to have helped for me (as above). Would anyone know how I might be able to get this working?

**Comment by ebonyclock** [comment]
Are you sure Boost.chrono was installed? Do you have for example this header boost/chrono/include.hpp somewhere in your system?
If not try to install boost.chrono itself : sudo apt-get install libboost-chrono-dev.

**Comment by tycho01** [comment]
Glad to learn it can be installed separately as well; think that should put me on the right track. Thanks. :)
