### ISSUE TITLE
set_windows_visible(False) has no effect on OSX

### ISSUE THREAD

**Issue by wjaskowski** [Marqt/ViZDoom#61]

**Comment by rex8312** [comment]
It is not working on Windows 10, too.

**Comment by jietang** [comment]
The Cocoa backend for Mac doesn't appear to support window hiding.

As a workaround you can install sdl2 (brew install sdl2) and build VizDoom using the SDL2 backend with the cmake flag -DOSX_COCOA_BACKEND=OFF

**Comment by Marqt** [comment]
Thank you @jietang for finding that option - OSX_COCOA_BACKEND is OFF by default now. 
`set_windows_visible(False)` should work with SDL2 backend - can anyone confirm?

And Windows has been fixed - thanks for info @rex8312, I will prepare new bin release soon.

**Comment by wjaskowski** [comment]
It works!
