### ISSUE TITLE
doom.set_seed() does not work as expected

### ISSUE THREAD

**Issue by wjaskowski** [Marqt/ViZDoom#65]
doom.set_seed(seed) makes all the following episodes the same! It seems that the random generator is seeded with that seed on each new_episode().

**Comment by Marqt** [comment]
This is intentional and it's exactly how it works - if seed is set, it is used as init value for each episode. That it is not mentioned in example, but seed can be cleared by calling `set_seed(0)` (Should we add `clear_seed()`?).

To set specific seed and disable it's "resetting" use:
```
game.set_seed(seed)
game.new_episode()
game.set_seed(0)
```

**Comment by wjaskowski** [comment]
This is counterintuitive. The random generator once seeded should not be
reset to some old seed.

**Comment by Marqt** [comment]
This design was influenced by ZDoom's rng design. 
You're right, it should work in more expected way - I will change it:
`set_seed(seed)` will be setting seed only for next `new_episode()`.

**Comment by wjaskowski** [comment]
set_seed(seed) should influence all subsequent episodes like random.seed()
influence all subsequent random.random() calls.

**Comment by pliskowski** [comment]
Typical design is to seed the random data generator with the given seed only once when the game is created. After each call to the `new_episode()` the seeded generator should be used to randomize the initial state of the next episode. In this way, the sequence of episodes and their states will be deterministic.

**Comment by Marqt** [comment]
Ok, I've changed it, now `set_seed(seed)` sets seed for rng that generates seeds for episodes.

> After each call to the new_episode() the seeded generator should be used to randomize the initial state of the next episode. In this way, the sequence of episodes and their states will be deterministic.

So, it works as you described @pliskowski, however `set_seed(seed)` can be still used during runtime to affect the next episodes.

Thank you @wjaskowski and @pliskowski
