### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by muupan** [Marqt/ViZDoom#66]
It would be great if ViZDoom could support Python3

**Comment by ebonyclock** [comment]
I'll try to make it happen.

**Comment by Marqt** [comment]
If you rebuild Boost.Python with Python3 you should be able to build Python3 bindings for ViZDoom without the problem, (setting paths to Python3 dirs for cmake may be needed). We tested it a long time ago.

**Comment by muupan** [comment]
I needed at least these changes in CMaleList.txt to build with Python 3.5.1.

```
-       find_package(PythonInterp 2.7 REQUIRED)
-       find_package(PythonLibs 2.7 REQUIRED)
+       find_package(PythonInterp 3.5 REQUIRED)
+       find_package(PythonLibs 3.5 REQUIRED)
```
```
-       find_package(Boost COMPONENTS python REQUIRED)
+       find_package(Boost COMPONENTS python3 REQUIRED)
```
```
-               ${Boost_PYTHON_LIBRARY}
+               ${Boost_PYTHON3_LIBRARY}
```

**Comment by Marqt** [comment]
Yeah, also this needs to be changed. 
I think we will add this as option in cmake.

**Comment by danijar** [comment]
A CMake option would be awesome. Did this already happen?

**Comment by ebonyclock** [comment]
Almost. Current version look for the first available python starting with 2.7. To force python 3  just change line 111 to:
find_package(PythonInterp 3 REQUIRED)


The option itself will come soon when I tidy Boost on my system and make sure it behaves how we want.

**Comment by danijar** [comment]
Thanks, looking forward.

**Comment by ebonyclock** [comment]
BUILD_PYTHON3 flag has been added, it will force building python3 version and place it in ../bin/python3
