### ISSUE TITLE
Accessing Agent's Global Map Position

### ISSUE THREAD

**Issue by SimsGautam** [Marqt/ViZDoom#67]
How would I go about accessing the X,Y position of the agent (with respect to the global map) at any state? I believe what i'm looking for is GetActorX() and GetActorY() defined here (http://zdoom.org/wiki/GetActorX), but I couldn't figure out how to access these values from a script like basic.py.

Thanks!

**Comment by ebonyclock** [comment]
The idea is that you can't. You are supposed to only use the visual input and some info like hp or ammo so you cannot access it from e.g. basic.wad scenario (or any other created by us). However, you can design your own wad that lets you do it:
1. In your scenario (wad file) in acs define a global variable 1-32 like this:
global int 1:my_fancy_custom_variable_whose_name_doesnt_matter;
2. Assign (every tic if needed) whatever value you want (e.g. GetActorX()).
3. Access your variable by USER1-32 game variables either in state or via get_game_variable(...).

Note that ACS does not support floats and uses ints to represent fixed point numerals. If you want to get some value that is actually fixed point not int (and I believe that X & Y coordinates are fixed point numerals) use doom_fixed_to_double.

**Comment by SimsGautam** [comment]
Thanks for the quick response! I tried something like this 
```
global int 1:x_pos;
global int 2:y_pos;

script 2 ENTER
{
    x_pos = 3;
y = 4;
    while(1)
    {
        delay(1);
        actorx = 4;
		actory = GetActorY(0);
		print(2);
    }    
}
```

And I try to access these variable doing something like
`doom_fixed_to_double(game.get_game_variable(GameVariable.USER1)))`

**Comment by ebonyclock** [comment]
Very strange. I copy pasted your code and it works for me. Are you sure you compiled the thing?

**Comment by SimsGautam** [comment]
I am compiling with acc 1.55 (download from http://zdoom.org/Download). As a sanity check, I just opened basic.wad in slade to edit and compile the acs script. When I tried compiling it, I got the following error.

`Couldn't find include file "zcommon.acs".`

If I take out "zcommon.acs" and make the acs script exactly as defined in the earlier post, then I can compile properly. Then when I run the python file, I get the following error. 

```
*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x1b9d578

Generating vizdoom-crash.log and killing process 8177, please wait... 40	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
sh: 1: gxmessage: not found
Traceback (most recent call last):
  File "doom.py", line 100, in <module>
    game.init()
vizdoom.ViZDoomUnexpectedExitException: Controlled ViZDoom instance exited unexpectedly.
```

I am using Mac OSX to make changes to the wad files, and I'm using Ubuntu (14.04) for ViZDoom. Help is appreciated. Thank you!

**Comment by ebonyclock** [comment]
I think that "zcommon.acs" is essential, instead of removing it make sure it is present in your acs  compiler's directory.  And by the way, don't you get any errors while compiling without including zcommon.acs? 

I got this kind of error when I messed up the scenario badly and it crashed. Are you able to at least run the wad in vizdoom/zdoom in your edditing tool (not via api)?

**Comment by ebonyclock** [comment]
Did you manage to do something with it?

**Comment by SimsGautam** [comment]
Yup, ended up figuring it out. BTW, we've made use of ViZDoom for http://arxiv.org/pdf/1606.02396v1.pdf. Thanks!

**Comment by ebonyclock** [comment]
Cool! Must read it!

**Comment by glample** [comment]
I'm facing exactly the same error message, but I can't fix it. How were you able to solve the problem?
Note that the bug is only when I create a new wad file from scratch, and does not appear when I modify the code of any of the given wad files.

**Comment by glample** [comment]
Okay I found the issue. It looks like the problem happens when the map is not created properly.

**Comment by GoingMyWay** [comment]
I tried this to get the position of player

```
print("Player position X:", game.get_game_variable(GameVariable.POSITION_X),
                              "Y:", game.get_game_variable(GameVariable.POSITION_Y),
                              "Z:", game.get_game_variable(GameVariable.POSITION_Z))
```
