### ISSUE TITLE
Windows binary download link is worng.

### ISSUE THREAD

**Issue by rex8312** [Marqt/ViZDoom#68]
This is current windows binary download link in README.MD.

https://github.com/Marqt/ViZDoom/releases/download/1.0.1/ViZDoom-1.0.2-Win-x86_64.zip

Probably, 1.0.1 --> 1.0.2 is correct.

https://github.com/Marqt/ViZDoom/releases/download/1.0.2/ViZDoom-1.0.2-Win-x86_64.zip

**Comment by Marqt** [comment]
Definitely the second one should be in readme, thank you for noticing!
