### ISSUE TITLE
sporadic incorrect depth data

### ISSUE THREAD

**Issue by cjdarken** [Marqt/ViZDoom#72]
Zip archive: 
[depthbug.zip](https://github.com/Marqt/ViZDoom/files/284792/depthbug.zip)

These files document a sporadic depth buffer value problem that I have encountered running ViZDoom with Python bindings on a Windows 10 machine with an Intel HD 6000 graphics card. The symptom is that only two unique values appear in the depth image, one for the HUD bar at the bottom of the image, and one other value for the rest of the image. Two images are provided showing how the application renders good and bad depth buffer data.

Replication Instructions
1) Clone ViZDoom from github
2) Unpack the distributed Windows binaries (version 1.0.2) on top
3) Add freedoom2.wad to the scenarios directory
4) Unpack depthbug.zip to the examples directory
5) Copy vizdoom.pyd to the examples directory (or otherwise make sure Python can find it)
6) From the depthbug directory, execute "python depthbug.py"
7) You will need to run the application multiple times to see the problem. Note the histogram of depth buffer values that is printed to the console. This is the easiest path to verifying the bug (rather than verifying all the manipulations required to render the depth buffer to the screen).

**Comment by oOo0oOo** [comment]
Without running your code I have experienced something similar.
In my case the output was either always correct or always incorrect.
Thus I have just repeatedly set up the game until I got the correct output on a test frame.
V dirty workaround...

**Comment by cjdarken** [comment]
When you say that you repeatedly set up the game, do you mean within a single run? If that can be made to work, I might give it a try. I have been just killing and restarting the app, hoping for a good run, but that is getting a bit old. And of course, that approach doesn't work for a competition.

**Comment by wjaskowski** [comment]
The depth buffer is disallowed for the competition. Sorry if that was not
clear enough.

**Comment by cjdarken** [comment]
Thanks for clarifying this point. That certainly makes sense though, given the goals of the competition.

**Comment by oOo0oOo** [comment]
I just checked and the hack didn't work anymore.
Used to check if the frame was just one color via numpy.std(self._cur_frame) == 0...

I understand that the depth buffer is not allowed during the competition;
what about the training phase? 
Going down that road: simultaneous depth and image buffer readout without running
two instances on the same seed would be amazing!

**Comment by ebonyclock** [comment]
During the training you can use whatever the depth buffer (even if we wanted to abolish this we wouldn't have any way to enforce it).

You can use the proper image with ZBuffer, just use ScreenFormats: CRCGCBDB (4 channels of 8-bit values in RGB + depth buffer order) or CBCGCRDB ( 4 channels of 8-bit values in BGR + depth buffer order).

**Comment by oOo0oOo** [comment]
Thanks for the info! I'll give CRCGCBDB a try...

**Comment by wjaskowski** [comment]
No restrictions on training.

**Comment by wjaskowski** [comment]
I cannot reproduce this problem either on Linux nor on OSX. I have no Windows to check but maybe it is Windows-related.

**Comment by Marqt** [comment]
I've just tested all formats containing depth buffer (50 times each) on Windows 7 and it works totally fine for me (I used modified format.py example for this). Graphic card and drivers should be irrelevant, couse all rendering is made on cpu (on linux ViZDoom can even run without graphic card and xserver).

So it's strange...
Are you both using Windows 10?

**Comment by oOo0oOo** [comment]
I have had time to look at this again and keep running into the same issues.
Running a vizdoom version from around 2 weeks ago on Ubuntu 14.04..  

It shows some really strange behaviour when using the CRCGCBDB screen format. Seemingly random but I have found some correlations..

- The first three channels (normal image data) are always correct.
- The depth data is either correct during the whole episode or only returns
        a matrix of all equal values. (Usually either 1 or some large value).
        I use this property to create (and close) new instances of DoomGame until I hit one that works.
- The behaviour seems to be **dependent on the scenario**:
      "basic" always (?) works, "health_gathering" and "cig" much less often, but if you keep trying they             eventually work.
-  **set_window_visible(False)** seems to improve the probability of correct depth buffer access.
- This one I'm not too sure about but deleting vizdoom.ini & _vizdoom.ini might also help...

If needed I can write a minimal example later on..

**Comment by Marqt** [comment]
I cannot reproduce this bug anymore (tested on Linux and Windows).
