### ISSUE TITLE
Packages for Ubuntu, Arch, etc.

### ISSUE THREAD

**Issue by danijar** [Marqt/ViZDoom#76]
Are there any plans to package ViZDoom and submit it to the common package repositories?

**Comment by wjaskowski** [comment]
I do not think so. Too much maintenance overhead.


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by danijar** [comment]
@wjaskowski Understandable. Thanks for your response.
