### ISSUE TITLE
Is there a way to install ViZDoom system-wide?

### ISSUE THREAD

**Issue by danijar** [Marqt/ViZDoom#77]
I managed to compiled the project on Linux including the Python bindings and have all the files in `<repo>/bin`. How can I now install ViZDoom globally?

**Comment by ebonyclock** [comment]
I guess you want to be able to import it from wherever you are. Is so just symlink or copy vizdoom.so to wherever your python modules are, etc. /usr/lib/pymodules/python2.7/

**Comment by danijar** [comment]
So I don't need any other files than `vizdoom.so` globally available?

**Comment by ebonyclock** [comment]
Yes. 
However you have to remember about the stuff that is in config files like scenario and main resources wad to do anything sensible.

**Comment by danijar** [comment]
Okay, cool. Maybe we want to add a command for this to the CMake script?

**Comment by ebonyclock** [comment]
I don't feel like adding anything that makes system-wide changes (however small) is a good idea. I'd rather live this to users that are aware of what they're doing.

**Comment by danijar** [comment]
Well, that's the idea of *installing*. Of course only copy the files on `make install` which is the default for CMake's [`install()` command](https://cmake.org/cmake/help/v3.0/command/install.html).

**Comment by ebonyclock** [comment]
ViZDoom is now pip-installable.
