### ISSUE TITLE
Resolve paths in config files relative to the files rather than the working directory

### ISSUE THREAD

**Issue by danijar** [Marqt/ViZDoom#78]
My bot lives in its own repository rather than in the examples directory. For this to work, I symlinked `<path-to-vizdoom>/bin/python/vizdoom.so` into the directory of my bot.

Now it would be nice if I could use the config files that come with VizDoom directly, i.e. just load them by absolute paths in `game.load_config()`. However, the configs contain some file paths:

```cfg
vizdoom_path = ../../bin/vizdoom
doom_game_path = ../../scenarios/freedoom2.wad
doom_scenario_path = ../../scenarios/basic.wad
```

The problem is that those paths are resolved relative to my working directory (the directory of my bot) rather than the directory of the config. Is this hard to fix? I might be able to provide some help to fix this.

**Comment by ebonyclock** [comment]
It's the expected behavior so it won't be fixed but I can make it look in the directory relative to the config file if it doesn't find anything in the path relative to the working directory.

**Comment by wjaskowski** [comment]
I don't like this idea. This double-policy can be bug-prone.


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by danijar** [comment]
@ebonyclock Interesting. Is there a special reason for this default behavior? It just seems counter-intuitive to me that the very same config file can reference different ViZDoom installation depending on my working directory. Especially since it's looking for the installation two paths upward, so that we/users are quite limited in what directory to execute the bots from.

**Comment by wjaskowski** [comment]
We should consider having something like VIZDOOM_HOME environment variable
instead of forcing to put the paths in the config.

**Comment by danijar** [comment]
This would be better than it is now. The `doom_game_path` and `doom_scenario_path` would then be resolved relative to `VIZDOOM_HOME` I guess? But I thought you wanted to keep the relative to the working directory.

Maybe we just want to add standard locations for the three paths. For example, install ViZDoom to `/usr/bin/vizdoom` and look for WAD files in `~/.config/vizdoom/`. The user could then easily add new scenarios. In a config, paths would be resolved relative to that directory. Or, if you argue that WAD files are too large to be dotfiles, have a `~/.config/vizdoom/vizdoom.conf` containing the path to the WAD file directory. What do you think?

**Comment by danijar** [comment]
This would be better than it is now. The `doom_game_path` and `doom_scenario_path` would then be resolved relative to `VIZDOOM_HOME` I guess? That would already be very helpful.

As a cleaner/long-term solution one might want to introduce standard paths. For example, install ViZDoom binaries to `/usr/bin/vizdoom` and look for WAD files in `~/.config/vizdoom/` which is the relative root for paths in config files. What do you think?

**Comment by wjaskowski** [comment]
On 4 June 2016 at 12:30, Danijar Hafner <notifications@github.com> wrote:

> This would be better than it is now. The doom_game_path and
> doom_scenario_path would then be resolved relative to VIZDOOM_HOME I
> guess? That would already be very helpful.
>
> As a cleaner/long-term solution one might want to introduce standard
> paths. For example, install ViZDoom binaries to /usr/bin/vizdoom and look
> for WAD files in ~/.config/vizdoom/ which is the relative root for paths
> in config files. What do you think?
>
This sounds right the me. Then vizdoom would be simply in PATH and
VIZDOOM_HOME would not be necessary. The question is whether to put WAD
files and other resources in HOME or somewhere system wide.

**Comment by danijar** [comment]
I think most Linux tools look in `~/.config/<tool-name>/` and `/etc/<tool-name>/` with the home directory taking preference over the system-wide location if a file exists in both paths. I'll try and find an official convention if there is but it seems reasonable to me.

**Comment by danijar** [comment]
@wjaskowski Any news on this?

**Comment by ebonyclock** [comment]
Not yet, sorry.

**Comment by Marqt** [comment]
Done a long time ago (1.1-dev branch).
