### ISSUE TITLE
Players spawn at the same location in deathmatch maps.

### ISSUE THREAD

**Issue by ebonyclock** [Marqt/ViZDoom#79]

**Comment by 5vision** [comment]
The one way to deal with the same location problem is customize `SelectRandomDeathmatchSpot` function in `g_game.cpp`.  To be precise, when a player spawn [at level start](https://github.com/Marqt/ViZDoom/blob/master/src/vizdoom/src/g_game.cpp#L1630).

This issue relates to the **telefrag** feature. Whether it will be used for CIG competition?

**Comment by ebonyclock** [comment]
I hope we will be able to disable telefraging soon.

**Comment by ebonyclock** [comment]
Actually we don't care that much. Telefraging is doom specific and is regonized by the system so it will stay.
