### ISSUE TITLE
Game crash at some situation.

### ISSUE THREAD

**Issue by Hilary93** [Marqt/ViZDoom#83]
I just tried to run ViZDoom and came across a problem. 
After i type:
**>> python spectator.py** 
```
*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x8

Generating vizdoom-crash.log and killing process 6235, please wait... 40	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
sh: 1: gxmessage: not found
Traceback (most recent call last):
  File "spectator.py", line 40, in <module>
    game.init()
vizdoom.ViZDoomErrorException: Controlled ViZDoom instance reported error.

```

Probably there is problem with displaying windows. It always crashed after trying to display one. I decided to change config file:
**window visible = true** into **window visible = false**
Then everything works "correctly", except for not being able to display window.

Few days ago application worked correctly. I did not upgrade or downgrade any system drivers. Does it look like bug in this application or some bigger problem with system?

I attach "vizdoom-crash.log" that spawned after ViZDoom crashes.
[vizdoom-crash.log.txt](https://github.com/Marqt/ViZDoom/files/303721/vizdoom-crash.log.txt)

**Comment by wjaskowski** [comment]
Interesting. Does ``bin/vizdoom`` run correctly on your system?

This seems related to the original ZDoom (http://forum.zdoom.org/viewtopic.php?t=47728&p=811365), but no solution was provided there. You should probably try to compile ZDoom and check if you get the same problem. If you do, then maybe you should try to ask on the ZDoom forum.

**Comment by ebonyclock** [comment]
Actually it's started to work ok automagically the next day without any recompilation and git pulls and Hilary93 can't reproduce it any more.
