### ISSUE TITLE
Access to the top down map 

### ISSUE THREAD

**Issue by shehroze37** [Marqt/ViZDoom#84]
In the binding file, the button binding for top down map is listed but cant get access to the map. How can I get the top down map ?

**Comment by Marqt** [comment]
It's not available as a button for agent, but you can use `game.send_command("togglemap")`.

**Comment by shehroze37** [comment]
Yesh I think getting access to the top down map will be useful as well.
is it possible to get the map from the game state ?
Cheers :-)

**Comment by shehroze37** [comment]
When I call game.send_game_command("togglemap") it gives me a segmentation fault.

**Comment by wjaskowski** [comment]
>
> When I call game.send_game_command("togglemap") it gives me a segmentation
> fault.
>
Works for me. Could you show an example that triggers the segfault? (Btw.
note that map nor any command are unavailable during the competition).

**Comment by shehroze37** [comment]
I'm running it in the spectator file with deadly corridor scenario.


game.send_game_command("togglemap")

game.add_game_args("+freelook 1")

game.set_screen_resolution(ScreenResolution.RES_640X480)
game.set_render_hud(False)
game.set_render_weapon( True )
game.set_window_visible(True)
game.set_mode(Mode.SPECTATOR)


game.init()

**Comment by wjaskowski** [comment]
Put it after init() and new_episode()

**Comment by shehroze37** [comment]
The binding for the map is tab but still not getting the map when I press tab. Do I need to change something in the binding file?

**Comment by ebonyclock** [comment]
No. W don't expose this button. It may change in the future though.

**Comment by Marqt** [comment]
Only buttons added as available works in spectator mode. Additional bindings like togglemap, toggleconsole or showscores are disabled - commands are blocked, so game.send_command("tooglemap") will not work. In player mode commands are not filtered.

I have the idea to render the map on the another buffer and make it available as an additional channel. Possible that I will add it, but not in the near future.

**Comment by Marqt** [comment]
Top down map is now implemented as separate buffer on [1.1-dev](https://github.com/Marqt/ViZDoom/tree/1.1-dev) branch. See buffers.py example. Additional options will be added to the api soon.

**Comment by shehroze37** [comment]
Its giving an error when I try to compile

ViZDoomNew/include/ViZDoomDefines.h:57:35: error: ‘nullptr’ was not declared in this scope
             this->screenBuffer  = nullptr;

**Comment by Marqt** [comment]
Configuration options have been added some time ago. I think this feature is complete.

**Comment by shehroze37** [comment]
The map for deathmatch is only partial. It does not show the whole environment !

**Comment by Marqt** [comment]
Somehow I did not notice that. Fixed, now map will follow the player.
Thank you @shehroze37.

**Comment by QingyuanWuNothing** [comment]
Dear maintainer, would you mind giving some examples that how to access the top-down map? The link shown above cannot be accessed. Cheers :)

**Comment by mwydmuch** [comment]
Dear @QingyuanWuNothing, sorry for the long response time. Please see:
https://github.com/Farama-Foundation/ViZDoom/blob/master/examples/python/automap_buffer.py - in this example, a top-down map is rendered as a buffer (an image).

and:

https://github.com/Farama-Foundation/ViZDoom/blob/master/examples/python/objects_and_sectors.py - in this example, a map is provided as a set of vertices and edges.
