### ISSUE TITLE
Make VizDoom pip-installable

### ISSUE THREAD

**Issue by jietang** [Marqt/ViZDoom#85]
For OpenAI Gym, we've published a small wrapper package for VizDoom that makes it possible to install VizDoom via pip (https://github.com/openai/doom-py). This greatly simplifies the process of installing gym dependencies.

Would you be interested in incorporating these changes into VizDoom proper? 

(would probably need someone on the VizDoom side to figure out the right way to do it since I doubt you want the top level to be a python package)

**Comment by wjaskowski** [comment]
Sounds wonderful! But pip should not install the java wrapper but only the
python one, right?

> I doubt you want the top level to be a python package

Hmm. I do not get it.

**Comment by jietang** [comment]
Yes, pip install would only install the Python wrapper.

Specifically, I propose adding a setup.py file at the top level of the package which invokes cmake to build libvizdoom with python bindings. A maintainer would need to manually increment the version number and run the necessary commands to upload a source-only distribution to pypi when the underlying VizDoom code has changed enough to warrant a new version.

If this sounds good to you I can work on a pull request.

**Comment by wjaskowski** [comment]
Great, go ahead!

**Comment by ebonyclock** [comment]
Basically done.
