### ISSUE TITLE
Map 01 cig.wad not working

### ISSUE THREAD

**Issue by shehroze37** [Marqt/ViZDoom#86]
When I try to run spectator with map 01 with cig.wad, it crashes. If this is normal then why does it say on the competition page that the limited deathmatch will be map 01 of cig.wad ?

Cheers !

**Comment by Marqt** [comment]
Are you trying to run it in singleplayer or multiplayer mode? If you are doing it in single it will probably crash cause there is no starting point for singleplayer on this map - we are working to handle this situation (we've discovered this recently).

**Comment by ebonyclock** [comment]
To clarify: the scenario requires running a deathmatch so when you try to run without -deathmatch option (like in spectator.py example) it will fail.

**Comment by shehroze37** [comment]
The full deathmatch map has some problems as well when I run it with the deathmatch scenario.

**Comment by ebonyclock** [comment]
What problems specifically?

**Comment by ebonyclock** [comment]
No info provided. Closing.
