### ISSUE TITLE
ViZDoom crash when MOVE_FORWARD button pressed

### ISSUE THREAD

**Issue by rex8312** [Marqt/ViZDoom#87]
I'm using ViZDoom 1.0.3 and 1.1.0pre in Windows 10.

When after AI hit the button MOVE_FORWARD, game crashed with this message.
"ViZDoomUnexpectedExitException: Controlled ViZDoom instance exited unexpectedly."

It happen when I try to run shaping.py.
MOVE_BACKWARD or MOVE_FORWARD_BACKWARD_DELTA is working.

**Comment by ebonyclock** [comment]
Yes, it happens not only for shaping.py but generally when using MOVE_FORWARD. It works ok on Linux though.

**Comment by Marqt** [comment]
I think it is the same issue as #74, it should work now correctly in new 1.1.0pre build (
it has been updated) and in 1.0.4 version.

**Comment by rex8312** [comment]
I see, probably, I have some mistake while update ViZDoom.
It's work after update again. Thanks.

**Comment by Marqt** [comment]
@rex8312: Thank You for confirming.
