### ISSUE TITLE
Fixed newEpisode with a bug

### ISSUE THREAD

**Issue by 5vision** [Marqt/ViZDoom#88]
There is a bug in the commit [71abb61](https://github.com/Marqt/ViZDoom/tree/71abb61e92b4fd6d5e0548760b0195b264eaac3b) that leads to unexpected behavior (memory leak, ViZDoomErrorException, etc.) in game.new_episode().

Adding `this->sendCommand(std::string("map ") + this->map)` seems to be fixes it.

Could you please explain for what it is intended?

**Comment by ebonyclock** [comment]
Is the memory leak in vizdoom process?

How do you produce it? I have experienced a similar thing but it happens very rarely and it was hard to track it.

**Comment by 5vision** [comment]
Yes, the memory leak in vizdoom and it leaks very quickly. We just run the default example/python/learning.py. In the previous commit 61098a3 there is additional [command](https://github.com/Marqt/ViZDoom/commit/71abb61e92b4fd6d5e0548760b0195b264eaac3b?diff=split#diff-dc20e11dab0a4894ed6ee9e6b25f3b05L365). Is it important?

**Comment by ebonyclock** [comment]
I don't think that it's important. Anyway thanks for reporting this, it happens much faster that in my setup so it'll be easier to track it down. And now I know that it's not my system's issue.

**Comment by ebonyclock** [comment]
As for "this->sendCommand(std::string("map ") + this->map)" it was meant as a workaround for freezing new episodes but it seams that removing it was a bad decision.

**Comment by Marqt** [comment]
In the early stages of ViZDoom, I encountered strange problem - "never ending" map restarting and this code was added as workaround. I've checked a couple of times recently if this is still happening and I've not noticed it again so I've decided to removed this - sorry, looks like it is still important.

**Comment by Marqt** [comment]
@5vision: Thank You very much for noticing and investigating.
